options:
  smtp_smarthost:
    description: |
      The default SMTP smarthost used for sending emails, including port number.
      Port number usually is 25, or 587 for SMTP over TLS (sometimes referred to as STARTTLS).
      Example: smtp.example.org:587
  smtp_from:
    description: The default SMTP From header field.
  smtp_auth_username:
    description: SMTP Auth using CRAM-MD5, LOGIN and PLAIN. If empty, Alertmanager doesn't authenticate to the SMTP server.
  smtp_auth_password:
    description: SMTP Auth using LOGIN and PLAIN.

